### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by UndeadNightFury** [Nihlus/digos-ambassador#49]
Please attach the generated report to this issue!

**Describe the bug**

**To Reproduce**
2. Run command '....'
3. With parameters '....'

**Expected behavior**

**Screenshots**

**Additional context**
    Automatic bug report
====================

Generated at: 07/09/2019 20:19:14
Bot version: 2.0.0.0
Command message link: https://discordapp.com/channels/556204320887013385/557507609444483123/619990075064844318
Ran by: Undead Night Fury#0238 (303913182211211265)
In: Night Fury Death Knights (556204320887013385)
Full command: !help

### Stack Trace
Discord.Net.HttpException: The server responded with error 50013: Missing Permissions
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, String bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, RequestOptions options)
   at Discord.WebSocket.SocketTextChannel.Discord.IMessageChannel.SendMessageAsync(String text, Boolean isTTS, Embed embed, RequestOptions options)
   at DIGOS.Ambassador.Discord.Feedback.UserFeedbackService.SendEmbedAsync(IMessageChannel channel, Embed eb) in /opt/digos/src/Discord/DIGOS.Ambassador.Discord.Feedback/UserFeedbackService.cs:line 178
   at DIGOS.Ambassador.Discord.Feedback.UserFeedbackService.SendEmbedAsync(ICommandContext context, Color color, String contents) in /opt/digos/src/Discord/DIGOS.Ambassador.Discord.Feedback/UserFeedbackService.cs:line 217
   at DIGOS.Ambassador.Discord.Feedback.UserFeedbackService.SendConfirmationAsync(ICommandContext context, String contents) in /opt/digos/src/Discord/DIGOS.Ambassador.Discord.Feedback/UserFeedbackService.cs:line 134
   at DIGOS.Ambassador.Discord.Interactivity.InteractivityServiceExtensions.SendPrivateInteractiveMessageAndDeleteAsync(InteractivityService this, ICommandContext context, UserFeedbackService feedback, InteractiveMessage message, Nullable`1 timeout) in /opt/digos/src/Discord/DIGOS.Ambassador.Discord.Interactivity/InteractivityServiceExtensions.cs:line 114
   at DIGOS.Ambassador.Discord.Interactivity.InteractivityServiceExtensions.SendPrivateInteractiveMessageAndDeleteAsync(InteractivityService this, ICommandContext context, UserFeedbackService feedback, InteractiveMessage message, Nullable`1 timeout) in /opt/digos/src/Discord/DIGOS.Ambassador.Discord.Interactivity/InteractivityServiceExtensions.cs:line 130
   at DIGOS.Ambassador.Modules.HelpCommands.HelpAsync() in /opt/digos/src/digos-ambassador/Modules/HelpCommands.cs:line 86
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteAsync(ICommandContext context, IEnumerable`1 argList, IEnumerable`1 paramList, IServiceProvider services)

**Comment by Nihlus** [comment]
This looks like the bot doesn't have permissions to send messages. Can you verify that?

**Comment by UndeadNightFury** [comment]
![2019-09-10 (1)](https://user-images.githubusercontent.com/52829173/64650988-76c7e600-d3ee-11e9-82c5-c78b83168300.png)

**Comment by Nihlus** [comment]
In general, the bot needs the following permissions. You should create a role for the bot, and assign it the following permissions.

Required:
- Read Text Channels & See Voice Channels
- Send Messages
- Embed Links
- Attach Files
- Read Message History
- Add Reactions

Optional
- Manage Messages (to delete command messages)
- Manage Roles (to swap user roles when changing characters with assigned roles)
- Manage Channels (to create new channels dynamically for roleplays)
- Manage Nicknames (to swap user nicknames when changing characters)

**Comment by UndeadNightFury** [comment]
ive already given it the bots role and i just double checked too make sure it gives all the listed perms and it dose yet the problem still happens

**Comment by Nihlus** [comment]
I can't reproduce it, unfortunately. It is defintively something with your permission setup - is it just this one channel, or the whole server?

**Comment by UndeadNightFury** [comment]
ok i figured it out by checking the bot on my mods channel and it worked thx!

**Comment by Nihlus** [comment]
Ah, good to hear!
