### ISSUE TITLE
Automated bug report from a character change.

### ISSUE THREAD

**Issue by ExcessiveElectrons** [Nihlus/digos-ambassador#96]
Please attach the generated report to this issue!

**Describe the bug**

**To Reproduce**
What I did: 
Ran a !ch assume command for one of my characters. 
ran it again thinking that I mistyped it.
Checked if bot was alive by trying to bap myself, shortly after that I got a notification that the bot hit an error.

**Expected behavior**
I expected to switch to another character.

**Screenshots**

**Additional context**
Automatic bug report
====================

Generated at: 13/03/2021 05:50:24
Bot version: 2.0.0.0
Command message link: [redacted]
Ran by: [redacted]
In: Transformations (183031180814319616)
Full command: !ch assume [redacted]

### Stack Trace
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure.
 ---> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Npgsql.PostgresException (0x80004005): 40001: could not serialize access due to concurrent update
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
  Exception data:
    Severity: ERROR
    SqlState: 40001
    MessageText: could not serialize access due to concurrent update
    File: nodeModifyTable.c
    Line: 1370
    Routine: ExecUpdate
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at DIGOS.Ambassador.Plugins.Characters.Services.CharacterService.ClearCurrentCharacterAsync(User user, Server server, CancellationToken ct) in /opt/digos/src/Plugins/DIGOS.Ambassador.Plugins.Characters/Services/CharacterService.cs:line 362
   at DIGOS.Ambassador.Plugins.Characters.Services.CharacterService.MakeCharacterCurrentAsync(User user, Server server, Character character, CancellationToken ct) in /opt/digos/src/Plugins/DIGOS.Ambassador.Plugins.Characters/Services/CharacterService.cs:line 337
   at DIGOS.Ambassador.Plugins.Characters.Services.CharacterDiscordService.MakeCharacterCurrentAsync(IGuildUser guildUser, Character character, CancellationToken ct) in /opt/digos/src/Plugins/DIGOS.Ambassador.Plugins.Characters/Services/CharacterDiscordService.cs:line 656
   at DIGOS.Ambassador.Plugins.Characters.CommandModules.CharacterCommands.AssumeCharacterFormAsync(Character character) in /opt/digos/src/Plugins/DIGOS.Ambassador.Plugins.Characters/CommandModules/CharacterCommands.cs:line 533
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteAsync(ICommandContext context, IEnumerable`1 argList, IEnumerable`1 paramList, IServiceProvider services)

**Comment by Nihlus** [comment]
This is in all likelihood a transient error.
